version: '3'

services:
    app:
        image: node:16-alpine
        environment:
            VIRTUAL_HOST: app-vueje-template.${ENVIRONMENT_URL} # Expose container
        command: npm run dev # Start app compilation on container startup
        labels:
            # Set aliases to use binaries in container directly from terminal
            protocode.alias.node: "docker-compose run --rm -it app node" # Use "node" instead of "docker-compose run --rm -it app node"
            protocode.alias.npm: "docker-compose run --rm -it app npm" # Same for npm, npx or yarn
            protocode.alias.npx: "docker-compose run --rm -it app npx"
            protocode.alias.yarn: "docker-compose run --rm -it app yarn"
        volumes:
            - '.:/app'
        working_dir: /app
