version: '3'

services:
    app:
        image: node:16-alpine
        environment:
            VIRTUAL_HOST: app.local
        labels:
            # Set aliases to use binaries within container from environment terminal
            protocode.alias.node: "docker-compose run --rm -u $(id -u):$(id -g) -it app node"
            protocode.alias.npm: "docker-compose run --rm -u $(id -u):$(id -g) -it app npm"
            protocode.alias.npx: "docker-compose run --rm -u $(id -u):$(id -g) -it app npx"
            protocode.alias.yarn: "docker-compose run --rm -u $(id -u):$(id -g) -it app yarn"
        volumes:
            - '.:/app'
        working_dir: /app
